version: "3.3" 

services:
  update:
    image: node:16.18.0
    container_name: readholdings-update-dev
    environment:
      - NODE_ENV=development
      # elastic
      - ELASTICSEARCH_HOST
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      # mail
      - MAIL_APIKEY
      # database
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      # holdingsAPI
      - EBSO_API_BASEURL
      # TODO
      - CONFIG_PATH
      # FIXME
      - INSHS_CUSTID
      - INSHS_APIKEY
      # proxy
      - http_proxy
      - https_proxy
    working_dir: /update
    volumes:
      - ./src/update:/update
    command: "npm run dev"
    ports:
      - ${UPDATE_PORT:-3000}:3000
    depends_on:
      - elastic
    restart: unless-stopped

  mail:
    image: node:16.18.0
    container_name: readholdings-mail-dev
    environment:
      # mail
      - NODE_CONFIG
      - SMTP_HOST=maildev
      - SMTP_PORT
      - NOTIFICATIONS_SENDER
      - NOTIFICATIONS_RECEIVERS
      - NOTIFICATIONS_MACHINE
    working_dir: /mail
    volumes:
      - ./src/mail:/mail
    command: "npm run dev"
    ports:
      - ${MAIL_PORT:-8000}:8000
    restart: unless-stopped

  database:
    image: postgres:14.4
    container_name: readholdings-database-dev
    ports:
      - ${PGADIN_EMAIL:-5432}:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-database}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: readholdings-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-changeme}
    ports:
      - ${PGADIN_PORT:-5050}:80
    restart: unless-stopped

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: readholdings-elastic-dev
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./data/elastic:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: readholdings-kibana-dev
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic:9200"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=true
    depends_on:
      - "elastic"
    restart: unless-stopped

  maildev:
    image: djfarrelly/maildev
    container_name: readholdings-maildev-dev
    ports:
      - 1080:80
